### ISSUE TITLE
貌似体验地址不能正常打开了

### ISSUE THREAD

**Issue by unmurphy** [fandypeng/excel2config#2]

**Comment by HeyChengdu** [comment]
返回错误
{"code":-500,"message":"-500","ttl":1,"data":null}


curl 'http://47.98.195.95:8000/excel' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Accept: */*' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36' \
  -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
  -H 'Origin: http://e2c.fandypeng.com' \
  -H 'Referer: http://e2c.fandypeng.com/' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-US;q=0.7,zh-TW;q=0.6,ja;q=0.5,es;q=0.4' \
  --data-raw 'gridKey=comment' \
  --compressed \
  --insecure

**Comment by fandypeng** [comment]
> 返回错误
> {"code":-500,"message":"-500","ttl":1,"data":null}
> 
> curl 'http://47.98.195.95:8000/excel'
> -H 'Connection: keep-alive'
> -H 'Pragma: no-cache'
> -H 'Cache-Control: no-cache'
> -H 'Accept: _/_'
> -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36'
> -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8'
> -H 'Origin: http://e2c.fandypeng.com'
> -H 'Referer: http://e2c.fandypeng.com/'
> -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-US;q=0.7,zh-TW;q=0.6,ja;q=0.5,es;q=0.4'
> --data-raw 'gridKey=comment'
> --compressed
> --insecure

time="2020-12-28T14:56:29+08:00" level=error msg="mango decode error" err="error decoding key config.sheetViewZoom.viewNormalZoomScale: IntDecodeValue can only truncate float64 to an integer type when truncation is enabled" source="mongo.go:79"

time="2020-12-28T14:56:29+08:00" level=error msg="mango decode error" err="error decoding key config.sheetViewZoom.viewNormalZoomScale: IntDecodeValue can only truncate float64 to an integer type when truncation is enabled" source="mongo.go:79"

原因是config.sheetViewZoom.viewNormalZoomScale类型定义错误，应该为浮点型

**Comment by unmurphy** [comment]
嗯～，在你基础上部分数据类型重新改了一下，目前正常了
