### ISSUE TITLE
体验地址登录不进去

### ISSUE THREAD

**Issue by ChenWeihua123** [fandypeng/excel2config#6]
控制台报错：network error
Access to XMLHttpRequest at 'http://e2c.fandypeng.com:8000/user/login' from origin 'http://e2c.fandypeng.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by fandypeng** [comment]
最近没有维护，服务器进程挂掉了，现在可以登进去啦
